export const GET_AVAILABLE_TIMESLOTS_REQUEST =
  "GET_AVAILABLE_TIMESLOTS_REQUEST";
export const GET_AVAILABLE_TIMESLOTS_SUCCESS =
  "GET_AVAILABLE_TIMESLOTS_SUCCESS";
export const GET_AVAILABLE_TIMESLOTS_FAIL = "GET_AVAILABLE_TIMESLOTS_FAIL";

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";
export const RESET_NEW_BOOKING = "RESET_NEW_BOOKING";
